FROM node:latest

WORKDIR /frontend

# Copy the local code
# COPY ./frontend .

# Install dependencies
# RUN npm run build

# Expose the app port
# EXPOSE 3000

# Run the React app
# CMD ["npm", "start"]
