version: '3'

services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacts
      MYSQL_USER: api
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: on-failure
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env_docker
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings_docker
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    command: ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start

